name: Deploy to Azure VM

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AZURE_VM_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.AZURE_VM_HOST }} >> ~/.ssh/known_hosts

    - name: Clear and copy frontend code
      run: |
        ssh ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_HOST }} "rm -rf /home/suvadip/cv_maker_frontend/*"
        scp -r ./client/* ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_HOST }}:/home/suvadip/cv_maker_frontend/

    - name: Build frontend on VM and deploy to NGINX folder
      run: |
        ssh ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_HOST }} << 'EOF'
          cd /home/suvadip/cv_maker_frontend
          if [ ! -d "node_modules" ]; then
            echo "Installing dependencies..."
            npm ci --prefer-offline
          else
            echo "Dependencies already installed, skipping npm install."
          fi
          npm run build
          sudo rm -rf /var/www/html/*
          sudo cp -r build/* /var/www/html/
        EOF

    - name: Clear and copy backend code
      run: |
        ssh ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_HOST }} "rm -rf /home/suvadip/cv_maker_backend/*"
        scp -r ./server/* ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_HOST }}:/home/suvadip/cv_maker_backend/

    - name: Install backend deps and restart with PM2
      run: |
        ssh ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_HOST }} << 'EOF'
          cd /home/suvadip/cv_maker_backend
          if [ ! -d "node_modules" ]; then
            echo "Installing backend dependencies..."
            npm ci --prefer-offline
          else
            echo "Backend dependencies already installed, skipping npm install."
          fi
          pm2 describe app > /dev/null && pm2 restart app || pm2 start app.js --name app
        EOF
